artifact_location: /home/dusarpi/data.talks/mlops-zoomcamp/02-experiment-tracking/http./127.0.0.1:5000/0
creation_time: 1748591298072
experiment_id: '0'
last_update_time: 1748591298072
lifecycle_stage: active
name: Default
